# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font-family: \"Verdana\";\n"
"background: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("font-family: \"Verdana\";")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.imgArea_HLayout = QtWidgets.QHBoxLayout()
        self.imgArea_HLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.imgArea_HLayout.setObjectName("imgArea_HLayout")
        self.btn_arrowL = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_arrowL.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arrowL.sizePolicy().hasHeightForWidth())
        self.btn_arrowL.setSizePolicy(sizePolicy)
        self.btn_arrowL.setMaximumSize(QtCore.QSize(25, 250))
        self.btn_arrowL.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_arrowL.setStyleSheet("QPushButton {\n"
"    margin: 1px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 9px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 6px;\n"
"}")
        self.btn_arrowL.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow l.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_arrowL.setIcon(icon)
        self.btn_arrowL.setIconSize(QtCore.QSize(25, 25))
        self.btn_arrowL.setObjectName("btn_arrowL")
        self.imgArea_HLayout.addWidget(self.btn_arrowL)
        self.stackedWid_images = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWid_images.sizePolicy().hasHeightForWidth())
        self.stackedWid_images.setSizePolicy(sizePolicy)
        self.stackedWid_images.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(245, 245, 245);")
        self.stackedWid_images.setLineWidth(0)
        self.stackedWid_images.setObjectName("stackedWid_images")
        self.imgArea_HLayout.addWidget(self.stackedWid_images)
        self.btn_arrowR = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_arrowR.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arrowR.sizePolicy().hasHeightForWidth())
        self.btn_arrowR.setSizePolicy(sizePolicy)
        self.btn_arrowR.setMaximumSize(QtCore.QSize(25, 250))
        self.btn_arrowR.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_arrowR.setStyleSheet("QPushButton {\n"
"    margin: 1px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 9px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 6px;\n"
"}")
        self.btn_arrowR.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow r.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_arrowR.setIcon(icon1)
        self.btn_arrowR.setIconSize(QtCore.QSize(25, 25))
        self.btn_arrowR.setObjectName("btn_arrowR")
        self.imgArea_HLayout.addWidget(self.btn_arrowR)
        self.gridLayout.addLayout(self.imgArea_HLayout, 0, 0, 1, 1)
        self.imgName_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.imgName_label.setFont(font)
        self.imgName_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.imgName_label.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(220, 230, 240);\n"
"padding: 4px;")
        self.imgName_label.setText("")
        self.imgName_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imgName_label.setObjectName("imgName_label")
        self.gridLayout.addWidget(self.imgName_label, 1, 0, 1, 1)
        self.data_VLayout = QtWidgets.QVBoxLayout()
        self.data_VLayout.setSpacing(7)
        self.data_VLayout.setObjectName("data_VLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(220, 230, 240);\n"
"padding: 5px;")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.data_VLayout.addWidget(self.label)
        self.cur_depth = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.cur_depth.setMinimumSize(QtCore.QSize(0, 35))
        self.cur_depth.setMaximumSize(QtCore.QSize(296, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cur_depth.setFont(font)
        self.cur_depth.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(245, 245, 245);\n"
"padding: 5px;")
        self.cur_depth.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cur_depth.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.cur_depth.setLineWidth(1)
        self.cur_depth.setMidLineWidth(0)
        self.cur_depth.setSmallDecimalPoint(True)
        self.cur_depth.setDigitCount(6)
        self.cur_depth.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.cur_depth.setProperty("value", 0.0)
        self.cur_depth.setProperty("intValue", 0)
        self.cur_depth.setObjectName("cur_depth")
        self.data_VLayout.addWidget(self.cur_depth)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(220, 230, 240);\n"
"padding: 5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.data_VLayout.addWidget(self.label_2)
        self.listWidget_rec = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_rec.setMaximumSize(QtCore.QSize(296, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.listWidget_rec.setFont(font)
        self.listWidget_rec.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(245, 245, 245);\n"
"padding: 5px;")
        self.listWidget_rec.setBatchSize(250)
        self.listWidget_rec.setSelectionRectVisible(False)
        self.listWidget_rec.setObjectName("listWidget_rec")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_rec.addItem(item)
        self.data_VLayout.addWidget(self.listWidget_rec)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(220, 230, 240);\n"
"padding: 5px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.data_VLayout.addWidget(self.label_3)
        self.listWidget_coor = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_coor.setMaximumSize(QtCore.QSize(296, 300))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.listWidget_coor.setFont(font)
        self.listWidget_coor.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(245, 245, 245);\n"
"padding: 5px;")
        self.listWidget_coor.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.listWidget_coor.setBatchSize(250)
        self.listWidget_coor.setObjectName("listWidget_coor")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_coor.addItem(item)
        self.data_VLayout.addWidget(self.listWidget_coor)
        self.data_VLayout.setStretch(1, 2)
        self.data_VLayout.setStretch(3, 15)
        self.data_VLayout.setStretch(5, 10)
        self.gridLayout.addLayout(self.data_VLayout, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setStyleSheet("border-radius: 12px;\n"
"background: rgb(200, 210, 220);")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.navBtn_HLayout = QtWidgets.QHBoxLayout()
        self.navBtn_HLayout.setObjectName("navBtn_HLayout")
        self.btn_open = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open.sizePolicy().hasHeightForWidth())
        self.btn_open.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_open.setFont(font)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_open.setStyleSheet("QPushButton {\n"
"    padding: 7px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.btn_open.setAutoDefault(False)
        self.btn_open.setDefault(False)
        self.btn_open.setFlat(False)
        self.btn_open.setObjectName("btn_open")
        self.navBtn_HLayout.addWidget(self.btn_open)
        self.btn_saveImg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_saveImg.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_saveImg.setFont(font)
        self.btn_saveImg.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_saveImg.setStyleSheet("QPushButton {\n"
"    padding: 7px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.btn_saveImg.setObjectName("btn_saveImg")
        self.navBtn_HLayout.addWidget(self.btn_saveImg)
        self.btn_saveData = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_saveData.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_saveData.setFont(font)
        self.btn_saveData.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_saveData.setStyleSheet("QPushButton {\n"
"    padding: 7px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.btn_saveData.setObjectName("btn_saveData")
        self.navBtn_HLayout.addWidget(self.btn_saveData)
        self.btn_rerec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_rerec.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_rerec.setFont(font)
        self.btn_rerec.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_rerec.setStyleSheet("QPushButton {\n"
"    padding: 7px;\n"
"    background: rgb(160, 170, 180);\n"
"      border-radius: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 210, 220);\n"
"    border: 1px solid black;\n"
"    border-radius: 7px;\n"
"}")
        self.btn_rerec.setObjectName("btn_rerec")
        self.navBtn_HLayout.addWidget(self.btn_rerec, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addLayout(self.navBtn_HLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWid_images.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LocMap"))
        self.label.setText(_translate("MainWindow", "Глубина в выбранной точке:"))
        self.label_2.setText(_translate("MainWindow", "Распознанные значения:"))
        __sortingEnabled = self.listWidget_rec.isSortingEnabled()
        self.listWidget_rec.setSortingEnabled(False)
        item = self.listWidget_rec.item(0)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(1)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(2)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(3)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(4)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(5)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(6)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(7)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(8)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(9)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(10)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(12)
        item.setText(_translate("MainWindow", "12"))
        item = self.listWidget_rec.item(13)
        item.setText(_translate("MainWindow", "12"))
        self.listWidget_rec.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Координаты глубин:"))
        __sortingEnabled = self.listWidget_coor.isSortingEnabled()
        self.listWidget_coor.setSortingEnabled(False)
        item = self.listWidget_coor.item(0)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(1)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(2)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(3)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(4)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(5)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        item = self.listWidget_coor.item(6)
        item.setText(_translate("MainWindow", "[[496.0, 1.0], [528.0, 6.0], [525.0, 26.0], [493.0, 22.0]]"))
        self.listWidget_coor.setSortingEnabled(__sortingEnabled)
        self.btn_open.setText(_translate("MainWindow", "Открыть"))
        self.btn_saveImg.setText(_translate("MainWindow", "Сохранить изображения"))
        self.btn_saveData.setText(_translate("MainWindow", "Сохранить значения"))
        self.btn_rerec.setText(_translate("MainWindow", "Перераспознать"))
